services:
  vector_db:
    image: qdrant/qdrant
    container_name: vector_db
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - "./qdrant_storage:/qdrant/storage:z"
    restart: unless-stopped
  ingestion:
    build:
      context: ./ingestion 
      dockerfile: Dockerfile 
    command: sh -c "sleep 15 && python ingestion.py"
    environment:
      - QDRANT_URL=http://vector_db:6333
      - COLLECTION_NAME=met-museum-artworks
      - DATA_PATH=/app/data/met_museum_objects_full.json 
    volumes:
      - ./data:/app/data 